blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions
    about: Use GitHub discussions for message-board style questions and discussions.
    url: https://github.com/orgs/enthusiasticcodelab/discussions/categories/q-a
